// <auto-generated />
using KartverketGruppe1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KartverketGruppe1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241024162024_NyeTables")]
    partial class NyeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KartverketGruppe1.Data.Kommune", b =>
                {
                    b.Property<int>("Kommune_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Kommune_ID"));

                    b.Property<string>("Kommunenavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kommunenummer")
                        .HasColumnType("int");

                    b.HasKey("Kommune_ID");

                    b.ToTable("Kommune");
                });

            modelBuilder.Entity("KartverketGruppe1.Data.Koordinat", b =>
                {
                    b.Property<int>("Koordinat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Koordinat_ID"));

                    b.Property<string>("Koordinater")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Koordinat_ID");

                    b.ToTable("koordinat");
                });

            modelBuilder.Entity("KartverketGruppe1.Data.Saksbehandler", b =>
                {
                    b.Property<int>("Saksbehandler_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Saksbehandler_ID"));

                    b.Property<string>("Ansvarsområde")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Avdeling")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Saksbehandler_ID");

                    b.ToTable("Saksbehandler");
                });
#pragma warning restore 612, 618
        }
    }
}
