services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbKartverket
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: kartverketgruppe1
      MYSQL_USER: root
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  kartverketgruppe1:
    image: ${DOCKER_REGISTRY-}kartverketgruppe1
    build:
      context: .
      dockerfile: KartverketGruppe1/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
     ConnectionStrings__DefaultConnection: "Server=mariadb;Database=kartverketgruppe1;User=root;Password=test123;"
    networks:
      - backend

volumes:
    mariadb_data:

networks:
  backend:
  # kartverketgruppe1:
  #   image: ${DOCKER_REGISTRY-}kartverketgruppe1
  #   build:
  #     context: .
  #     dockerfile: KartverketGruppe1/Dockerfile